### PR TITLE
Middleware x Backend x Testing

### LINKED ISSUE #4: backend - create new tables in database for reviews
- Dependency: Need to know what columns to add based on input from form

### LINKED ISSUE #5: frontend - write the angular controller to call middleware functions based on form input

### LINKED ISSUE #6: backend - write function that stores user input in database

### LINKED ISSUE #7: middleware - call api with new backend functions for reviews
depends on backend database, functions completion
add test file to test middleware-backend integration
Dependency: Has to have both functions from backend and form ready

### LINKED ISSUE #11: Create tests
Write tests to check that Reviews are added properly to the db and that tests are automated.

### PR DESCRIPTION
**Pull request by fuhaowei**
Middleware and backend merged with branch - mvn and build tested. please help me see if this is ok!

Fixed #4 
Fixed #6 
Fixed #7 
Fixed #11

### CODE REVIEW

**Review by walkingcabbages — CHANGES_REQUESTED** [review]
Please delete commented out lines / dead code.

**Review by walkingcabbages — APPROVED** [review]
LGTM! Even though tests don't pass, in interest of time, merging is good to go.

**Comment by fuhaowei** [comment]
Fixes #4 
Fixes #6 
Fixes #7 
Fixes #11

**Comment by fuhaowei** [comment]
Fixes #4

**Pull request merged**
